import mongoose, { Schema, Document } from 'mongoose';
import { IRefund } from './../types/refund.types';
import { IBase } from './base';

export interface RefundDocument extends Document {
    orderId: string;
    userId: string;
    refundAmount: number;
    reason: string;
    status: 'pending' | 'processing' | 'completed' | 'failed';
    adminNotes?: string;
    paymentGateway: string;
    gatewayTransactionId: string; // Original Payment ID
    gatewayRefundId?: string; // Refund ID from Razorpay
    failureReason?: string;
}



const refundSchema: Schema = new Schema<RefundDocument>({
  orderId: {
    type: mongoose.Schema.Types.ObjectId as any,
    ref: 'Order', // IMPORTANT: You must have an 'Order' model
    required: true,
  },
  userId: {
    type: mongoose.Schema.Types.ObjectId as any,
    ref: 'User', // IMPORTANT: You must have a 'User' model
    required: true,
  },
  refundAmount: {
    type: Number,
    required: true,
  },
  reason: {
    type: String,
    required: true,
  },
  status: {
    type: String,
    enum: ['pending', 'processing', 'completed', 'failed'],
    default: 'pending',
  },
  adminNotes: {
    type: String,
  },
  paymentGateway: {
    type: String,
    default: 'Razorpay',
  },
  gatewayTransactionId: {
    type: String,
    required: true, // The original payment ID from the order
  },
  gatewayRefundId: {
    type: String, // The ID generated by Razorpay for the refund
  },
  failureReason: {
      type: String, // To store error messages from the gateway
  }
}, {
  timestamps: true,
});

const RefundModel = mongoose.model<RefundDocument>('Refund', refundSchema);

export default RefundModel;