import mongoose from 'mongoose';
import { app } from './app';
import { config } from './config';
import { logger } from './config/logger';
import http from 'http';
import chalk from 'chalk';

import { initMarketingCron } from './cron/marketing.cron';
import { initLocationCron } from './cron/location.cron';



let isShuttingDown = false;

async function connectToDatabase(): Promise<void> {
  try {
    // Define mongoose connection options with proper typing
    const mongooseOptions: mongoose.ConnectOptions = {
      connectTimeoutMS: 10000,
      autoIndex: config.env === 'development',
      serverSelectionTimeoutMS: 5000,
      maxPoolSize: 10,
      minPoolSize: 2
    };

    await mongoose.connect(config.mongodb.uri, mongooseOptions);
    logger.info('Connected to MongoDB successfully');

    // MongoDB connection event handlers
    mongoose.connection.on('error', (err) => {
      logger.error({ error: err }, 'MongoDB connection error');
    });

    mongoose.connection.on('disconnected', () => {
      if (!isShuttingDown) {
        logger.warn('MongoDB disconnected. Attempting to reconnect...');
      }
    });


    mongoose.connection.on('reconnected', () => {
      logger.info('MongoDB reconnected successfully');
    });

    mongoose.connection.on('close', () => {
      logger.info('MongoDB connection closed');
    });

  } catch (error) {
    logger.error({
      error: error instanceof Error ? error.message : String(error),
      stack: error instanceof Error ? error.stack : undefined,
      uri: config.mongodb.uri.replace(/\/\/([^:]+):([^@]+)@/, '//******:******@')
    }, 'MongoDB connection error');
    process.exit(1);
  }
}

async function startServer(): Promise<void> {
  try {
    // Connect to MongoDB
    await connectToDatabase();
    // await ProductModel.collection.dropIndex("variants.sku_1");
    // Register routes generated by TSOA
    try {
      // RegisterMobileRoutes(app);
      // RegisterAdminRoutes(app);
      // registerCategoryRoutes(app);
      // logger.info('TSOA routes registered successfully');
    } catch (error) {
      logger.error({
        error: error instanceof Error ? error.message : String(error),
        stack: error instanceof Error ? error.stack : undefined
      }, 'Failed to register TSOA routes');
      throw error;
    }



    // Initialize Crons
    // initMarketingCron();
    // initLocationCron();

    // Start the server with proper typing
    const server: http.Server = app.listen(config.port, () => {
      logger.info({
        env: config.env,
        port: config.port,
        nodeVersion: process.version,
        memoryUsage: Math.round(process.memoryUsage().rss / (1024 * 1024)) + 'MB'
      }, `Server started - ${config.env} mode on port ${config.port}`);
      console.log(chalk.bold.green(`Server is running on port ${config.port}`));
      // Log available endpoints
      const baseUrl = `http://localhost:${config.port}/v1`;
      console.log(chalk.bold.green(`Check postman docs:  http://localhost:${config.port}/docs`));

      logger.info(`Mobile API: ${baseUrl}/mobile`);
      logger.info(`Admin API: ${baseUrl}/admin`);
      console.log(`\n🚀 Server is running on port ${config.port}`);

      console.log(`💊 Health Check: http://localhost:${config.port}/health`);
    });

    // Define types for shutdown handlers
    const gracefulShutdown = (signal: string): void => {
      if (isShuttingDown) return;
      isShuttingDown = true;

      logger.info(`${signal} received, shutting down gracefully`);
      server.close(() => {
        logger.info('HTTP server closed');
        mongoose.connection.close(false)
          .then(() => {
            logger.info('MongoDB connection closed');
            process.exit(0);
          })
          .catch((err) => {
            logger.error({ error: err }, 'Error during MongoDB connection close');
            process.exit(1);
          });
      });

      // Force shutdown after 10s if graceful shutdown fails
      setTimeout(() => {
        logger.error('Forcing shutdown after timeout');
        process.exit(1);
      }, 10000);
    };

    // Set up signal handlers for different termination signals
    process.on('SIGTERM', () => gracefulShutdown('SIGTERM'));
    process.on('SIGINT', () => gracefulShutdown('SIGINT'));

  } catch (error) {
    logger.error({
      error: error instanceof Error ? error.message : String(error),
      stack: error instanceof Error ? error.stack : undefined
    }, 'Failed to start server');
    process.exit(1);
  }
}

// Handle uncaught exceptions
process.on('uncaughtException', (error: Error) => {
  logger.error({
    error: error.message,
    stack: error.stack,
    type: 'uncaughtException'
  }, '💥 UNCAUGHT EXCEPTION! Shutting down...');

  // Give time to log then exit
  setTimeout(() => {
    process.exit(1);
  }, 1000);
});

// Handle unhandled promise rejections
process.on('unhandledRejection', (reason: any, promise: Promise<any>) => {
  logger.error({
    reason: reason instanceof Error ? reason.message : String(reason),
    stack: reason instanceof Error ? reason.stack : undefined,
    type: 'unhandledRejection'
  }, '💥 UNHANDLED REJECTION! Shutting down...');

  // Give time to log then exit
  setTimeout(() => {
    process.exit(1);
  }, 1000);
});

// Handle warnings
process.on('warning', (warning: Error) => {
  logger.warn({
    name: warning.name,
    message: warning.message,
    stack: warning.stack
  }, 'Process warning');
});

// Start the server
startServer().catch((error) => {
  console.error('Unhandled server startup error:', error);
  process.exit(1);
});